"use strict";
module.exports=function(sequelize, DataTypes)
{
	var Orders = sequelize.define('Orders',
	{
		customerId:
		{
			type:DataTypes.INTEGER,
			field:"customer_id"
		},
		employeeId:
		{
			type:DataTypes.INTEGER,
			field:"employee_id"
		},
		shipVia:
		{
			type:DataTypes.INTEGER,
			field:"ship_via"
		},
		orderDate:
		{
			type:DataTypes.DATE,
			field:"order_date"
		},
		requiredDate:
		{
			type:DataTypes.DATE,
			field:"required_date"
		},
		shippedDate:
		{
			type:DataTypes.DATE,
			field:"shipped_date"
		},
		freight:
		{
			type:DataTypes.DOUBLE,
			field:"freight"
		},
		shipName:
		{
			type:DataTypes.STRING,
			field:"ship_name"
		},
		shipAddress:
		{
			type:DataTypes.STRING,
			field:"ship_address"
		},
		shipCity:
		{
			type:DataTypes.STRING,
			field:"ship_city"
		},
		shipRegion:
		{
			type:DataTypes.STRING,
			field:"ship_region"
		},
		shipPostalCode:
		{
			type:DataTypes.STRING,
			field:"ship_postal_code"
		},
		shipCountry:
		{
			type:DataTypes.STRING,
			field:"ship_country"
		}
	},
	{
		tableName:"tbl_orders"
	},
	{
		classMethods:
		{
			associate:function(models)
			{
				Orders.belongTo(models.Employees,{forignKey:"employee_id"});
				Orders.belongTo(models.Customers,{forignKey:"customer_id"});
				Orders.belongTo(models.Shippers,{forignKey:"ship_via"});
				Orders.hasMany(models.OrderDetails,{forignKey:"order_id"});
			}
		}
	});
	return Orders;
}